#if !canImport(ObjectiveC)
import XCTest

extension URITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URITests = [
        ("testUrl", testUrl),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(URITests.__allTests__URITests),
    ]
}
#endif
