#if !canImport(ObjectiveC)
import XCTest

extension APIContractTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIContractTests = [
        ("testGetAPIContract", testGetAPIContract),
    ]
}

extension ClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClientTests = [
        ("testGet", testGet),
    ]
}

extension URITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URITests = [
        ("testUrl", testUrl),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APIContractTests.__allTests__APIContractTests),
        testCase(ClientTests.__allTests__ClientTests),
        testCase(URITests.__allTests__URITests),
    ]
}
#endif
